### PR TITLE
Improve user experience of OS version

### PR DESCRIPTION
**Pull request by helfi92**
Fixes https://github.com/mozilla-frontend-infra/balrog-ui/issues/192.

Screen Shot 2019-09-06 at 4 02 05 PM

Screen Shot 2019-09-06 at 4 02 32 PM

### CODE REVIEW

**Comment by helfi92** [comment]
> And I don't know if it's a huge pain in the butt or not, but allowing multiple entries on one line (and only using a second one if we'd start scrolling) would greatly improve the usage of space. Particularly for locales, a lot of horizontal space is wasted because they're only a few characters each. I'm thinking the wrapping would work like this in an ideal world:

Hm, I feel it's a bit unconventional to allow two separators (comma and new lines) which might add code complexity and confusion to users. I guess we can keep the current way and probably revisit if we hear complaints.

**Comment by mozbhearsum** [comment]
I'm not going to block on the comma and newline thing, but I'd like to see the first 3 points addressed:
* Put locale and osVersion beside one another
* Move them below the Version row again. I know this makes it slightly less visually appealing, but it maintains the sort-by-frequency-of-use ordering, which is more important IMO.
* Increase the number of rows.

I can drive this to completion, if you're tight on time.

**Comment by helfi92** [comment]
I failed to push the commit 😅 One sec.

**Comment by helfi92** [comment]
Done.

**Pull request merged**
