### PR TITLE
Sort list of suggestions that AutoCompleteText receives

### LINKED ISSUE #124: Sort list of suggestions that AutoCompleteText receives
Let's sort the list of suggestions that the AutoCompleteText component receives with `useMemo`.

Idea came from https://github.com/mozilla-frontend-infra/balrog-ui/pull/123#discussion_r308227550.

### PR DESCRIPTION
**Pull request by divyanshu-rawat**
Fixes #124.

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@helfi92 feel free to review. 👍

**Comment by divyanshu-rawat** [comment]
@helfi92 Happy new year 🎉 , I missed to review this PR 😅

**Comment by helfi92** [comment]
Happy new year :) I did, looking now!

**Comment by divyanshu-rawat** [comment]
Thanks ⚡️

**Comment by mozbhearsum** [comment]
Thank you @divyanshu-rawat!

**Comment by divyanshu-rawat** [comment]
Welcome :), It was nice working on the issue, I plan to pick up some other issues soon @mozbhearsum :)

**Pull request merged**
