### PR TITLE
Add initial layout for the releases view

### PR DESCRIPTION
**Pull request by helfi92**
Relates to https://github.com/mozilla-frontend-infra/balrog-ui/issues/58.

### CODE REVIEW

**Comment by helfi92** [comment]
> Home/end/pageup/pagedown don't behave as expected - they barely move the page at all.

What is "Home" and "end". Are those buttons on your keyboard?

> Noticed this exception in the console:

I'll send a patch here.

> A text field to filter by name -- this is crucial because of how many Releases we have.

Agreed. I will create a `Search` component in a follow-up and integrate it in this view.

> Hide/Disable the "Delete" button for Releases that are used by one or more Rules.

I'll send a patch here.

> Add a button for flipping the read-only/read-write flag.

Sounds good. I might tackle this in a follow-up.

> Handle scheduled changes.

We can take of that in a follow-up.

**Comment by mozbhearsum** [comment]
> What is "Home" and "end". Are those buttons on your keyboard?

Yes :).

**Comment by helfi92** [comment]
> Yes :).

Ah :( I figured out the issue but don't have a solution on top of my head. I will investigate more. Btw, this issue is probably also on the rules view as well now that the jump to hash has been merged.

**Comment by mozbhearsum** [comment]
> > Yes :).
> 
> Ah :( I figured out the issue but don't have a solution on top of my head. I will investigate more. Btw, this issue is probably also on the rules view as well now that the jump to hash has been merged.

Ah, indeed...

**Comment by helfi92** [comment]
To be done later:

* Add a button for flipping the read-only/read-write flag
* Handle scheduled changes

**Pull request merged**
